messages:
  menu_title: "=== Estado Esperado de Red ==="
  network_ip: "Ingrese la IP de la red: "
  select_os: "Seleccione los sistemas operativos permitidos (e.g 1 2 5): "
  select_services: "Seleccione los servicios permitidos (e.g 1 2 5): "
  select_ports: "Seleccione los puertos permitidos (e.g 1 2 5): "
  expected_devices: "Ingrese la cantidad esperada de dispositivos: "
  configured: "(Configurado)"
  cancel: "Cancelar"
  scan: "Escanear {targets}"
  selection_prompt: "Su selección: "
  max_attempts: "Máximo número de intentos excedidos."
  max_attempts_exit: "Saliendo debido a número de intentos excedido."
  network_ip_required: "1) Ip de Red (Necesario)"
  network_ip_configured: "1) Ip de Red (Configurado)"
  os_families: "2) Familias de OS"
  services: "3) Servicios "
  ports: "4) Puertos"
  devices_num: "5) Número de Dispositivos"
  break_option_cancel: "6) Cancelar"
  break_option_scan: "6) Escanear {targets}"
  cancel_operation: "Cancelando operación."